upd index.html
htmlacademy-htmlcss/2512281-sedona-1 pull request #2
Opened 2024-03-29 12:33 UTC by k-adelia

Накидала структуру в индекс, если ок - буду по такому же принципу формировать каталог

2024-04-14 21:30 UTC, k-adelia commented
Добавила картинок

2024-04-17 15:35 UTC, Kartaviy-arteom requested changes

2024-04-17 15:35 UTC, Kartaviy-arteom commented on images/HTMLAcademy.svg
именование файлов/папок https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-02

2024-04-17 15:35 UTC, Kartaviy-arteom commented on images/advantage_photo_1.jpg
именование(разделитель)

2024-04-17 15:35 UTC, Kartaviy-arteom commented on images/divider.png
векторное изображение

2024-04-17 15:35 UTC, Kartaviy-arteom commented on images/icons/heart.png
векторное изображение

2024-04-17 15:35 UTC, Kartaviy-arteom commented on index.html
> +    </style>
это необходимо вынести в файл стилей

2024-04-17 15:35 UTC, Kartaviy-arteom commented on index.html
> +        </ul>
расхождение с макетом

2024-04-17 15:35 UTC, Kartaviy-arteom commented on index.html
> +              <img alt="Поиск" src="images/icons/search.png">
декоративное изображение

2024-04-17 15:35 UTC, Kartaviy-arteom commented on index.html
> +              <img src="images/icons/heart.png" alt="Понравившиеся гостиницы">
декоративное изображение

2024-04-17 15:35 UTC, Kartaviy-arteom commented on index.html
> +              <button class="header-brown-btn">Хочу сюда</button>
ссылкой

2024-04-17 15:35 UTC, Kartaviy-arteom commented on index.html
> +        <img class="welcome" src="images/welcome.svg">
alt

2024-04-17 15:35 UTC, Kartaviy-arteom commented on index.html
> +      </section>
пустая секий, зачем она?

2024-04-17 15:35 UTC, Kartaviy-arteom commented on index.html
> +        </div>
список преимуществ

2024-04-17 15:35 UTC, Kartaviy-arteom commented on index.html
> +              <img src="images/Advantage-icon/house.svg">
декоративное изображение

2024-04-17 15:35 UTC, Kartaviy-arteom commented on index.html
> +      <section>
относится к вышестоящей секции

2024-04-17 15:35 UTC, Kartaviy-arteom commented on index.html
> +        <form action="#" type="post">
https://up.htmlacademy.ru/htmlcss-individual/1/criteries#HTML-04

2024-04-17 15:35 UTC, Kartaviy-arteom commented on index.html
> +          <input type="email">
подписи полей форм

2024-04-17 15:35 UTC, Kartaviy-arteom commented on index.html
> +        <li><a href="vk.com"><img alt="vk" src="images/vk-icon.svg"></a></li>
img не нужен

2024-04-17 15:35 UTC, Kartaviy-arteom commented on catalog.html
> +      </div>
форматирование документа

2024-04-17 15:35 UTC, Kartaviy-arteom commented on catalog.html
> +        <p><img src="images/home.svg"> > Гостиницы</p>
декоративная иконка

2024-04-17 15:35 UTC, Kartaviy-arteom commented on catalog.html
> +              <li><checkbox aria-checked="true">Бассейн</checkbox></li>
невалидная разметка. input

2024-04-17 15:35 UTC, Kartaviy-arteom commented on catalog.html
> +              <li><radiobutton checked="true">Гостиница</radiobutton></li>
input https://developer.mozilla.org/ru/docs/Web/HTML/Element/input

2024-04-17 15:35 UTC, Kartaviy-arteom commented on catalog.html
> +            <button onclick="serch()" class="search-button">Применить</button>
onclick="serch()" не нужно
тип для кнопки

2024-04-17 15:35 UTC, Kartaviy-arteom commented on catalog.html
> +          <div class="catalog-filter-price">
будет два инпута + две кнопки, сейчас можно пропустить

2024-04-17 15:35 UTC, Kartaviy-arteom commented on catalog.html
> +          <!--polzunok-->
https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-02

2024-04-17 15:35 UTC, Kartaviy-arteom commented on catalog.html
> +            <img src="images/view-list.svg">
картинки не нужны

2024-04-17 15:35 UTC, Kartaviy-arteom commented on catalog.html
> +            <select>
описание элемента https://up.htmlacademy.ru/htmlcss-individual/1/criteries#ALLY-02

2024-04-17 15:35 UTC, Kartaviy-arteom commented on catalog.html
> +              <button class="hotel-details">Подробнее</button>
ссылка

2024-04-17 15:35 UTC, Kartaviy-arteom commented on catalog.html
> +              <button class="hotel-to-fav">В избранное</button>
тип для кнопки

2024-04-17 15:35 UTC, Kartaviy-arteom commented on catalog.html
> +              <p>Hotel</p>
это не параграф, лучше просто спан

2024-04-17 15:35 UTC, Kartaviy-arteom commented on catalog.html
> +      <div class="phone-number-fiooter">+7 (912) 812-12-12</div>
ссылка

2024-04-17 15:35 UTC, Kartaviy-arteom commented on catalog.html
> +        <img src="images/HTMLAcademy.svg" width="170" height="70" alt="Логотип сайта команды разработки сайта">
обернуть в ссылку

2024-04-24 10:33 UTC, k-adelia commented on index.html
> +    </style>
Почему-то когда выношу стили не применяются к индексу

2024-04-24 10:37 UTC, k-adelia commented on index.html
> +    </style>
Почему-то при вынесении не применяются стили

2024-04-24 10:48 UTC, k-adelia commented on catalog.html
> +      </div>
Что с форматированием?

2024-04-24 11:11 UTC, k-adelia commented on catalog.html
> +              <button class="hotel-to-fav">В избранное</button>
submit?

2024-04-24 15:20 UTC, Kartaviy-arteom requested changes

2024-04-24 15:20 UTC, Kartaviy-arteom commented on catalog.html
> +          <h2>Найдено гостиниц: {{hotel_count}}</h2>
в данном окружении это не будет работать

2024-04-24 15:20 UTC, Kartaviy-arteom commented on catalog.html
> +            </a>
невалидная разметка

2024-04-24 15:20 UTC, Kartaviy-arteom commented on catalog.html
> +            <button class="btn-view btn-view-list" title="Список"></button>
это список и кнопкам нужны типы

2024-04-24 15:20 UTC, Kartaviy-arteom commented on catalog.html
> +            <img src="images/catalog/hotel-1.jpg">
alt обязательный атрибут + width & height

2024-04-24 15:20 UTC, Kartaviy-arteom commented on catalog.html
> +              <button class="hotel-to-fav">В избранное</button>
type=button

2024-04-24 15:20 UTC, Kartaviy-arteom commented on catalog.html
> +        <img src="divider-6.png">
это лишнее

2024-04-24 15:20 UTC, Kartaviy-arteom commented on catalog.html
> +            <li>{{index}}</li>
с нативным html само по себе это не работает, нужно соответствующее окружение

2024-04-24 15:20 UTC, Kartaviy-arteom commented on catalog.html
> +              <span class="sup-fav-count">11</span>
именование классов, сокращения не используются

2024-04-24 15:20 UTC, Kartaviy-arteom commented on catalog.html
> +          <input type="email">
label для input. required для обязательных полей

2024-04-24 15:20 UTC, Kartaviy-arteom commented on catalog.html
> +        <img src="images/htmlacademy.svg" width="170" height="70" alt="Логотип сайта команды разработки сайта">
логотип нужно обернуть в ссылку

2024-04-24 15:20 UTC, Kartaviy-arteom commented on catalog.html
> +      <div>
здесь необходимо соблюдать форматирование

2024-04-24 15:20 UTC, Kartaviy-arteom commented on catalog.html
> +        <form action="#" type="post">
у формы нет атрибута type

2024-04-24 15:20 UTC, Kartaviy-arteom commented on catalog.html
> +        <li><a href="vk.com"><img alt="vk" src="images/vk-icon.svg"></a></li>
img не нужен

2024-05-01 12:28 UTC, k-adelia commented on catalog.html
> +      <div>
> Гостиницы. Символ > есть в макете. Или его добавим позже через CSS
По идее путь можно сделать через список и каждый элемент списка начинать через этот символ:
> Гостиницы > Гостиница №2 > Удобства в гостинице №2

2024-05-05 20:08 UTC, k-adelia commented
Пока не закрою этот новый не создастся?

2024-05-06 16:07 UTC, Kartaviy-arteom requested changes
необходимо вот эти файлы переименовать в соответствии с критериями 
![image](https://github.com/htmlacademy-htmlcss/2512281-sedona-1/assets/46100724/3d2ff367-fa80-4890-8542-47881025a510)

2024-05-06 16:07 UTC, Kartaviy-arteom commented on styles/style.css
> +}
https://up.htmlacademy.ru/htmlcss-individual/1/criteries#CSS-02

2024-05-06 16:07 UTC, Kartaviy-arteom commented on styles/style.css
> +  background-color:rgba(117, 97, 87, 1);
https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-01, по всему файлу стилей. запись цветов и другие правила

2024-05-06 16:07 UTC, Kartaviy-arteom commented on styles/style.css
> +  font-family: "Roboto Bold", "Arial", sans-serif;
у нас нет roboto в макете и мы его не подключали. Везде используется PT Sans

2024-05-06 16:07 UTC, Kartaviy-arteom commented on catalog.html
> +    <link href="fonts/ptsans-400.woff2" rel="stylesheet">
это не нужно

2024-05-06 16:07 UTC, Kartaviy-arteom commented on styles/style.css
> +  src: url("font.woff2") format("woff2"),
пути у шрифтов не верные

2024-05-06 16:07 UTC, Kartaviy-arteom commented on styles/style.css
> +body {
блоки стлей разделяем пустой строкой https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-01

2024-05-06 16:07 UTC, Kartaviy-arteom commented on styles/style.css
> +  grid-template-columns: 33% 33% auto;
4 колонка будет 34 %.
grid-template-columns: repeat(3, 1fr);

2024-05-22 14:53 UTC, Kartaviy-arteom requested changes

2024-05-22 14:53 UTC, Kartaviy-arteom commented on index.html
> +        <img class="hero-img welcome" alt="Welcome to gorgeous Sedona" src="images/welcome.svg" width="458px" height="352px">
width="458px" height="352px" - принимают целые числа

2024-05-22 14:53 UTC, Kartaviy-arteom commented on index.html
> +          <form action="#" type="post">
эта форма не отправится, по тз формы должны отправляться. type="post" - такого атрибута нет

2024-05-22 14:53 UTC, Kartaviy-arteom commented on catalog.html
> +                <li><input type="checkbox" aria-checked="false">Wi-Fi</input></li>
инпуты не могут содержать в себе контент. aria-checked не используется вместе с type. + нужен label

2024-05-22 14:53 UTC, Kartaviy-arteom commented on catalog.html
> +              <li><button type="button" class="btn-view btn-view-tab catalog-view-selected" title="Таблица" type="button"></button></li>
дублирование атрибутов

2024-05-22 14:53 UTC, Kartaviy-arteom commented on index.html
> +          </li>
это все одна li

2024-05-22 14:53 UTC, Kartaviy-arteom commented on index.html
> +            </div>
ye;yj j,]tlbybnm d jlye дш

2024-05-22 14:55 UTC, Kartaviy-arteom requested changes

2024-05-22 14:55 UTC, Kartaviy-arteom commented on styles/style.css
> +    padding: 0;
по всему документу, необходимо выполнить критерий https://up.htmlacademy.ru/htmlcss-individual/1/criteries#PROJ-01

2024-05-22 14:55 UTC, Kartaviy-arteom commented on styles/style.css
> +}
для глобального селектора у img допустимо только
`img {
  max-width: 100%;
  height: auto;
  object-fit: contain;
}`

2024-05-29 15:08 UTC, merged